import os
from fastapi import FastAPI, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from google import genai
from google.genai.errors import APIError

app = FastAPI(title="Nexus AI Backend Proxy")

# Enable CORS so your GitHub Pages frontend can communicate with this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust to your GitHub Pages URL in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    prompt: str
    model: str = "gemini-2.5-flash"

@app.post("/api/chat")
async def chat_endpoint(
    request: ChatRequest,
    x_api_key: str | None = Header(default=None)
):
    """
    Relays chat requests to Google Gemini via the official SDK.
    Reads the API key from the request header 'X-API-Key' or environment variables.
    """
    api_key = x_api_key or os.getenv("GEMINI_API_KEY")
    
    if not api_key:
        raise HTTPException(
            status_code=401,
            detail="Missing Gemini API Key. Please pass it in the X-API-Key header or set GEMINI_API_KEY environment variable."
        )

    try:
        # Initialize Google GenAI client with the provided API Key
        client = genai.Client(api_key=api_key)
        
        # Generate content using the specified model
        response = client.models.generate_content(
            model=request.model,
            contents=request.prompt,
        )

        if not response.text:
            return {"success": False, "reply": "No text generated by model."}

        return {"success": True, "reply": response.text}

    except APIError as e:
        # Catch explicit Google Gemini API errors (invalid key, quota exceeded, model not found)
        raise HTTPException(
            status_code=e.code if hasattr(e, 'code') else 500,
            detail=f"Google Gemini API Error: {e.message}"
        )
    except Exception as e:
        # Catch unexpected runtime or network errors
        raise HTTPException(
            status_code=500,
            detail=f"Server error processing AI request: {str(e)}"
        )

if __name__ == "__main__":
    import uvicorn
    # Start server on http://localhost:8000
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
addasync function queryAI(prompt) {
  if (!state.apiKey) {
    return "Please open Settings ⚙️ and paste your Google Gemini API key to enable real AI generation.";
  }
  
  try {
    const res = await fetch("http://localhost:8000/api/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": state.apiKey
      },
      body: JSON.stringify({
        prompt: prompt,
        model: "gemini-2.5-flash"
      })
    });

    const data = await res.json();

    if (!res.ok) {
      return `Error (${res.status}): ${data.detail || "Server error"}`;
    }

    return data.reply;
  } catch (e) {
    return "Failed to reach local Python server. Ensure main.py is running on port 8000.";
  }
}addasync function queryAI(prompt) {
  if (!state.apiKey) {
    return "Please open Settings ⚙️ and paste your Google Gemini API key to enable real AI generation.";
  }
  
  try {
    const res = await fetch("http://localhost:8000/api/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-API-Key": state.apiKey
      },
      body: JSON.stringify({
        prompt: prompt,
        model: "gemini-2.5-flash"
      })
    });

    const data = await res.json();

    if (!res.ok) {
      return `Error (${res.status}): ${data.detail || "Server error"}`;
    }

    return data.reply;
  } catch (e) {
    return "Failed to reach local Python server. Ensure main.py is running on port 8000.";
  }
}

